### ISSUE TITLE
lambda:GetLayerVersion Error when adding as a layer

### ISSUE THREAD

**Issue by TeamXceleratorDev** [janaz/aws-lambda-node-runtime#5]
Hi, I am trying to add the latest US East 1 ARN to a Lambda function but receiving the error: lambda:GetLayerVersion.  I tried with 2 different AWS accounts.  Can you confirm that the layer is published with public access.

Thanks :)

**Comment by janaz** [comment]
Thanks for reporting it. It's probably an access issue, let me check...

**Comment by JanJakes** [comment]
Same problem with `eu-west-1`. The exact error:
```
You are not authorized to perform: lambda:GetLayerVersion.
```

**Comment by janaz** [comment]
I've done some investigation and was able to reproduce the problem. I need to execute
```sh
aws lambda add-layer-version-permission
```
on each published layer. I've also discovered another problem caused by recently moving from `7zip` to `advancecomp`. The latter doesn't retain executable flags on compressed files which makes the whole layer unusable. I will release new layers with updated node version later today. Stay tuned.

**Comment by janaz** [comment]
@JanJakes @TeamXceleratorDev Please check the layers from this release https://github.com/janaz/aws-lambda-node-runtime/releases/tag/node-14.7.0-aws-sdk-2.729.0

**Comment by TeamXceleratorDev** [comment]
Thanks.  I will give it a try in a day or two  :)

**Comment by TeamXceleratorDev** [comment]
I was able to verify it is working now. Thank you very much.  Closing issue.
